/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HabitTrackerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/view.ts
var import_obsidian2 = require("obsidian");

// src/calendar.ts
var MONTH_NAMES = ["\u042F\u043D\u0432\u0430\u0440\u044C", "\u0424\u0435\u0432\u0440\u0430\u043B\u044C", "\u041C\u0430\u0440\u0442", "\u0410\u043F\u0440\u0435\u043B\u044C", "\u041C\u0430\u0439", "\u0418\u044E\u043D\u044C", "\u0418\u044E\u043B\u044C", "\u0410\u0432\u0433\u0443\u0441\u0442", "\u0421\u0435\u043D\u0442\u044F\u0431\u0440\u044C", "\u041E\u043A\u0442\u044F\u0431\u0440\u044C", "\u041D\u043E\u044F\u0431\u0440\u044C", "\u0414\u0435\u043A\u0430\u0431\u0440\u044C"];
function getMonthName(date) {
  return MONTH_NAMES[date.month()];
}
function generateCalendar(date) {
  const start = date.clone().startOf("month");
  const end = date.clone().endOf("month");
  let firstDayIdx = start.day();
  firstDayIdx = firstDayIdx === 0 ? 6 : firstDayIdx - 1;
  const days = [];
  for (let i = 0; i < firstDayIdx; i++)
    days.push(null);
  for (let i = 1; i <= end.date(); i++) {
    days.push(date.clone().date(i));
  }
  return days;
}

// src/stats.ts
var import_obsidian = require("obsidian");
function calculateStatistics(notes, formatString) {
  if (notes.length === 0) {
    return { lastNoteDate: "", currentStreak: 0, timeSinceLastNote: "\u041D\u0435\u0442 \u0437\u0430\u043F\u0438\u0441\u0435\u0439" };
  }
  const formats = formatString.split("\n").map((f) => f.trim()).filter((f) => f.length > 0);
  const parsedNotes = notes.map((file) => {
    const name = file.name.replace(/\.md$/, "");
    for (const format of formats) {
      const m = (0, import_obsidian.moment)(name, format, true);
      if (m.isValid()) {
        let type = "day";
        if (format.includes("gggg-[W]ww") || format.includes("W"))
          type = "week";
        else if (format === "YYYY-MM")
          type = "month";
        else if (format.includes("Q"))
          type = "quarter";
        else if (format === "YYYY")
          type = "year";
        return { moment: m, type };
      }
    }
    return null;
  }).filter((n) => n !== null);
  parsedNotes.sort((a, b) => b.moment.valueOf() - a.moment.valueOf());
  if (parsedNotes.length === 0) {
    return { lastNoteDate: "", currentStreak: 0, timeSinceLastNote: "\u041D\u0435\u0442 \u0432\u0430\u043B\u0438\u0434\u043D\u044B\u0445 \u0434\u0430\u0442" };
  }
  const lastNote = parsedNotes[0].moment;
  const lastNoteDate = lastNote.format("DD MMM YYYY");
  const dailyNotesDates = parsedNotes.filter((n) => n.type === "day").map((n) => n.moment.format("YYYY-MM-DD"));
  const uniqueDates = new Set(dailyNotesDates);
  let currentStreak = 0;
  const today = (0, import_obsidian.moment)().startOf("day");
  const yesterday = today.clone().subtract(1, "day");
  const todayStr = today.format("YYYY-MM-DD");
  const yesterdayStr = yesterday.format("YYYY-MM-DD");
  if (uniqueDates.has(todayStr) || uniqueDates.has(yesterdayStr)) {
    currentStreak = 1;
    let checkDate = (uniqueDates.has(todayStr) ? today : yesterday).clone().subtract(1, "day");
    for (; ; ) {
      if (uniqueDates.has(checkDate.format("YYYY-MM-DD"))) {
        currentStreak++;
        checkDate.subtract(1, "day");
      } else {
        break;
      }
    }
  }
  const now = (0, import_obsidian.moment)();
  const diffDays = now.diff(lastNote, "days");
  let timeSinceLastNote;
  if (diffDays === 0)
    timeSinceLastNote = "\u0441\u0435\u0433\u043E\u0434\u043D\u044F";
  else if (diffDays === 1)
    timeSinceLastNote = "\u0432\u0447\u0435\u0440\u0430";
  else
    timeSinceLastNote = `${diffDays} \u0434\u043D. \u043D\u0430\u0437\u0430\u0434`;
  return { lastNoteDate, currentStreak, timeSinceLastNote };
}
function getNotesOnThisDay(notes) {
  const todayMonthDay = (0, import_obsidian.moment)().format("MM-DD");
  const todayDayMonth = (0, import_obsidian.moment)().format("DD.MM");
  return notes.filter((file) => {
    return file.name.includes(todayMonthDay) || file.name.includes(todayDayMonth);
  });
}
async function getRandomQualityNote(app, notes) {
  if (notes.length === 0)
    return null;
  for (let i = 0; i < 5; i++) {
    try {
      const randomNote = notes[Math.floor(Math.random() * notes.length)];
      const content = await app.vault.read(randomNote);
      if (content.length > 30)
        return randomNote;
    } catch (error) {
      console.error("Error reading file:", error);
    }
  }
  return notes[Math.floor(Math.random() * notes.length)];
}

// src/view.ts
var VIEW_TYPE_HABIT_TRACKER = "habit-tracker-view";
var HabitTrackerView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.dailyNotes = [];
    this.viewMode = "panorama";
    this.plugin = plugin;
    this.currentDate = (0, import_obsidian2.moment)();
  }
  getViewType() {
    return VIEW_TYPE_HABIT_TRACKER;
  }
  getDisplayText() {
    return "\u0422\u0440\u0435\u043A\u0435\u0440 \u041F\u0440\u0438\u0432\u044B\u0447\u0435\u043A";
  }
  async onOpen() {
    this.updateData();
    this.registerVaultEvent();
    await Promise.resolve();
  }
  registerVaultEvent() {
    this.eventRef = this.plugin.app.vault.on("create", (file) => {
      if (file.extension === "md") {
        const watchedFolders = this.plugin.settings.watchedFolders.split("\n").map((f) => f.trim());
        const isInWatchedFolder = watchedFolders.some((folder) => file.path.startsWith(folder));
        if (isInWatchedFolder) {
          this.updateData();
        }
      }
    });
    this.plugin.app.vault.on("modify", (file) => {
      if (file.extension === "md") {
        const watchedFolders = this.plugin.settings.watchedFolders.split("\n").map((f) => f.trim());
        const isInWatchedFolder = watchedFolders.some((folder) => file.path.startsWith(folder));
        if (isInWatchedFolder) {
          this.updateData();
        }
      }
    });
  }
  async onClose() {
    if (this.eventRef) {
      this.plugin.app.vault.offref(this.eventRef);
    }
    await Promise.resolve();
  }
  updateData() {
    this.dailyNotes = this.plugin.getDailyNotes();
    this.stats = calculateStatistics(this.dailyNotes, this.plugin.settings.dateFormats);
    this.render();
  }
  // Хелпер: Получить данные о файле (дата и тип)
  getFileData(file) {
    const formats = this.plugin.settings.dateFormats.split("\n").map((f) => f.trim()).filter((f) => f.length > 0);
    const name = file.name.replace(".md", "");
    for (const format of formats) {
      const m = (0, import_obsidian2.moment)(name, format, true);
      if (m.isValid()) {
        let type = "day";
        if (format.includes("W"))
          type = "week";
        else if (format.includes("Q"))
          type = "quarter";
        else if (format === "YYYY")
          type = "year";
        else if (format === "YYYY-MM")
          type = "month";
        if (type === "week")
          m.startOf("isoWeek");
        if (type === "month")
          m.startOf("month");
        if (type === "quarter")
          m.startOf("quarter");
        if (type === "year")
          m.startOf("year");
        return { date: m, type };
      }
    }
    return null;
  }
  render() {
    const container = this.containerEl;
    container.empty();
    container.addClass("habit-tracker-container");
    const header = container.createEl("div", { cls: "habit-tracker-header" });
    const row = header.createEl("div", { cls: "header-row" });
    const titles = {
      "panorama": "\u{1F3DB} \u041F\u0430\u043D\u043E\u0440\u0430\u043C\u0430 (3 \u043C\u0435\u0441\u044F\u0446\u0430)",
      "year": "\u{1F5FA} \u041A\u0430\u0440\u0442\u0430 \u0413\u043E\u0434\u0430",
      "overview": "\u{1F4C6} \u041E\u0431\u0437\u043E\u0440"
    };
    row.createEl("h2", { text: titles[this.viewMode] });
    const switcher = row.createEl("div", { cls: "mode-switcher" });
    switcher.createEl("button", { text: "3 \u043C\u0435\u0441", cls: `mode-btn ${this.viewMode === "panorama" ? "active" : ""}` }).onclick = () => {
      this.viewMode = "panorama";
      this.render();
    };
    switcher.createEl("button", { text: "\u041A\u0430\u0440\u0442\u0430 \u0433\u043E\u0434\u0430", cls: `mode-btn ${this.viewMode === "year" ? "active" : ""}` }).onclick = () => {
      this.viewMode = "year";
      this.render();
    };
    switcher.createEl("button", { text: "\u041E\u0431\u0437\u043E\u0440", cls: `mode-btn ${this.viewMode === "overview" ? "active" : ""}` }).onclick = () => {
      this.viewMode = "overview";
      this.render();
    };
    const mainContent = container.createEl("div", { cls: "habit-tracker-main" });
    if (this.viewMode === "panorama")
      this.renderPanorama(mainContent);
    else if (this.viewMode === "year")
      this.renderYearHeatmap(mainContent);
    else if (this.viewMode === "overview")
      this.renderMonthsOverview(mainContent);
    const sidebar = mainContent.createEl("div", { cls: "tracker-sidebar" });
    if (this.viewMode === "panorama") {
      sidebar.addClass("sidebar-retro-only");
      this.renderRetroModule(sidebar);
    } else {
      this.renderStatistics(sidebar);
    }
  }
  renderPanorama(container) {
    const nav = container.createEl("div", { cls: "panorama-nav" });
    nav.createEl("button", { text: "\u25C0 \u041A\u0432\u0430\u0440\u0442\u0430\u043B", cls: "mode-btn" }).onclick = () => {
      this.currentDate.subtract(3, "months");
      this.render();
    };
    nav.createEl("span", { text: "\u0421\u0435\u0433\u043E\u0434\u043D\u044F", cls: "mode-btn" }).onclick = () => {
      this.currentDate = (0, import_obsidian2.moment)();
      this.render();
    };
    nav.createEl("button", { text: "\u041A\u0432\u0430\u0440\u0442\u0430\u043B \u25B6", cls: "mode-btn" }).onclick = () => {
      this.currentDate.add(3, "months");
      this.render();
    };
    const currentYear = this.currentDate.year();
    const currentQuarter = this.currentDate.quarter();
    const quarterFile = this.dailyNotes.find((file) => {
      const data = this.getFileData(file);
      return data && data.type === "quarter" && data.date.year() === currentYear && data.date.quarter() === currentQuarter;
    });
    const quarterSection = container.createEl("div", { cls: "panorama-quarter-note" });
    if (quarterFile) {
      const quarterCard = quarterSection.createEl("div", {
        cls: "quarter-card-pano quarter-with-note-pano"
      });
      quarterCard.createEl("div", { cls: "quarter-title-pano", text: `\u{1F4CA} ${currentYear} Q${currentQuarter}` });
      quarterCard.createEl("div", { cls: "quarter-badge-pano", text: "\u2705 \u0415\u0441\u0442\u044C \u0437\u0430\u043C\u0435\u0442\u043A\u0430" });
      quarterCard.onmouseenter = () => {
        (async () => {
          try {
            const content = await this.plugin.app.vault.read(quarterFile);
            const preview = content.slice(0, 150).replace(/[#*`]/g, "");
            quarterCard.setAttribute("data-preview", preview + (content.length > 150 ? "..." : ""));
          } catch (error) {
            console.error("Error reading file:", error);
          }
        })().catch(() => {
        });
      };
      quarterCard.onclick = () => this.plugin.app.workspace.openLinkText(quarterFile.path, "", true);
    } else {
      const quarterCard = quarterSection.createEl("div", {
        cls: "quarter-card-pano quarter-empty-pano"
      });
      quarterCard.createEl("div", { cls: "quarter-title-pano", text: `\u{1F4CA} ${currentYear} Q${currentQuarter}` });
      quarterCard.createEl("div", { cls: "quarter-badge-pano quarter-empty-badge-pano", text: "\u274C \u041D\u0435\u0442 \u0437\u0430\u043C\u0435\u0442\u043A\u0438" });
      quarterCard.onclick = () => {
        const folders = this.plugin.settings.watchedFolders.split("\n");
        const path = `${folders[0].trim()}/${currentYear}-Q${currentQuarter}.md`;
        this.createNoteIfNotExists(path);
      };
    }
    const quarterStart = this.currentDate.clone().startOf("quarter");
    const grid = container.createEl("div", { cls: "calendars-grid" });
    for (let i = 0; i < 3; i++) {
      const monthDate = quarterStart.clone().add(i, "months");
      this.renderSingleMonth(grid, monthDate);
    }
  }
  renderYearHeatmap(container) {
    const wrapper = container.createEl("div", { cls: "heatmap-container" });
    const grid = wrapper.createEl("div", { cls: "heatmap-grid" });
    const notesMap = /* @__PURE__ */ new Map();
    this.dailyNotes.forEach((f) => {
      const data = this.getFileData(f);
      if (data)
        notesMap.set(data.date.format("YYYY-MM-DD"), { file: f, type: data.type });
    });
    const start = (0, import_obsidian2.moment)().startOf("year");
    const days = (0, import_obsidian2.moment)().endOf("year").dayOfYear();
    for (let i = 0; i < days; i++) {
      const d = start.clone().add(i, "days");
      const dStr = d.format("YYYY-MM-DD");
      const note = notesMap.get(dStr);
      const cell = grid.createEl("div", {
        cls: `heatmap-day ${note ? "active type-" + note.type : ""}`,
        attr: { "aria-label": `${d.format("D MMM")} ${note ? "\u2705" : ""}` }
      });
      if (note) {
        cell.onmouseenter = () => {
          (async () => {
            try {
              const content = await this.plugin.app.vault.read(note.file);
              const preview = content.slice(0, 150).replace(/[#*`]/g, "");
              cell.setAttribute("data-preview", preview + (content.length > 150 ? "..." : ""));
            } catch (error) {
              console.error("Error reading file:", error);
            }
          })().catch(() => {
          });
        };
        cell.onclick = () => this.plugin.app.workspace.openLinkText(note.file.path, "", true);
      }
    }
  }
  renderSingleMonth(parent, date) {
    const box = parent.createEl("div", { cls: "month-unit" });
    const monthHeader = box.createEl("div", { cls: "month-header-row" });
    new import_obsidian2.Setting(monthHeader).setHeading().setName(`${getMonthName(date)} ${date.year()}`).settingEl.addClass("month-label");
    const monthFile = this.dailyNotes.find((file) => {
      const data = this.getFileData(file);
      return data && data.type === "month" && data.date.year() === date.year() && data.date.month() === date.month();
    });
    const monthIcon = monthHeader.createEl("div", { cls: "month-note-icon" });
    if (monthFile) {
      monthIcon.addClass("month-note-exists");
      monthIcon.textContent = "\u{1F4CB}";
      monthIcon.onmouseenter = () => {
        (async () => {
          try {
            const content = await this.plugin.app.vault.read(monthFile);
            const preview = content.slice(0, 100).replace(/[#*`]/g, "");
            monthIcon.setAttribute("data-preview", preview + (content.length > 100 ? "..." : ""));
          } catch (error) {
            console.error("Error reading file:", error);
          }
        })().catch(() => {
        });
      };
      monthIcon.onclick = () => this.plugin.app.workspace.openLinkText(monthFile.path, "", true);
    } else {
      monthIcon.addClass("month-note-empty");
      monthIcon.textContent = "+";
      monthIcon.onclick = () => {
        const folders = this.plugin.settings.watchedFolders.split("\n");
        const path = `${folders[0].trim()}/${date.format("YYYY-MM")}.md`;
        this.createNoteIfNotExists(path);
      };
    }
    const grid = box.createEl("div", { cls: "calendar-grid mini-with-weeks" });
    ["\u041F\u043D", "\u0412\u0442", "\u0421\u0440", "\u0427\u0442", "\u041F\u0442", "\u0421\u0431", "\u0412\u0441", ""].forEach((t) => grid.createEl("div", { cls: "calendar-day-header", text: t }));
    const days = generateCalendar(date);
    const notesMap = /* @__PURE__ */ new Map();
    this.dailyNotes.forEach((f) => {
      const data = this.getFileData(f);
      if (data && data.type === "day") {
        notesMap.set(data.date.format("YYYY-MM-DD"), { file: f, type: data.type });
      }
    });
    const weekNotesMap = /* @__PURE__ */ new Map();
    this.dailyNotes.forEach((f) => {
      const data = this.getFileData(f);
      if (data && data.type === "week") {
        const weekYear = data.date.year();
        const weekNum = data.date.isoWeek();
        const weekKey = `${weekYear}-W${weekNum.toString().padStart(2, "0")}`;
        weekNotesMap.set(weekKey, f);
      }
    });
    const today = (0, import_obsidian2.moment)().format("YYYY-MM-DD");
    for (let i = 0; i < days.length; i += 7) {
      const weekDays = days.slice(i, i + 7);
      weekDays.forEach((d) => {
        const cell = grid.createEl("div", { cls: "calendar-day" });
        if (d) {
          const dStr = d.format("YYYY-MM-DD");
          const note = notesMap.get(dStr);
          cell.createEl("div", { text: d.date().toString() });
          if (note) {
            cell.addClass("calendar-day-with-note");
            cell.addClass(`type-${note.type}`);
            cell.onmouseenter = () => {
              (async () => {
                try {
                  const content = await this.plugin.app.vault.read(note.file);
                  const preview = content.slice(0, 150).replace(/[#*`]/g, "");
                  cell.setAttribute("data-preview", preview + (content.length > 150 ? "..." : ""));
                } catch (error) {
                  console.error("Error reading file:", error);
                }
              })().catch(() => {
              });
            };
            cell.onclick = () => this.plugin.app.workspace.openLinkText(note.file.path, "", true);
          } else {
            cell.onclick = () => this.createNote(dStr);
          }
          if (dStr === today)
            cell.addClass("calendar-day-today");
          cell.ariaLabel = dStr;
        }
      });
      const firstDayOfWeek = weekDays.find((d) => d !== null);
      if (firstDayOfWeek) {
        const weekDate = firstDayOfWeek.clone().startOf("isoWeek");
        const weekKey = `${weekDate.year()}-W${weekDate.isoWeek().toString().padStart(2, "0")}`;
        const weekFile = weekNotesMap.get(weekKey);
        const weekNum = weekDate.isoWeek();
        const weekCell = grid.createEl("div", { cls: "calendar-week-cell" });
        if (weekFile) {
          weekCell.addClass("week-cell-with-note");
          weekCell.createEl("div", { cls: "week-number", text: `W${weekNum.toString().padStart(2, "0")}` });
          weekCell.onmouseenter = () => {
            (async () => {
              try {
                const content = await this.plugin.app.vault.read(weekFile);
                const preview = content.slice(0, 80).replace(/[#*`]/g, "");
                weekCell.setAttribute("data-preview", preview + (content.length > 80 ? "..." : ""));
              } catch (error) {
                console.error("Error reading file:", error);
              }
            })().catch(() => {
            });
          };
          weekCell.onclick = () => this.plugin.app.workspace.openLinkText(weekFile.path, "", true);
        } else {
          weekCell.addClass("week-cell-empty");
          weekCell.createEl("div", { cls: "week-number", text: `W${weekNum.toString().padStart(2, "0")}` });
          weekCell.onclick = () => {
            const folders = this.plugin.settings.watchedFolders.split("\n");
            const path = `${folders[0].trim()}/${weekDate.format("gggg-[W]ww")}.md`;
            this.createNoteIfNotExists(path);
          };
        }
      } else {
        grid.createEl("div", { cls: "calendar-week-cell empty" });
      }
    }
  }
  // === КВАРТАЛЫ (отдельный вид) ===
  renderQuarters(container) {
    const wrapper = container.createEl("div", { cls: "periodic-container" });
    const nav = wrapper.createEl("div", { cls: "panorama-nav" });
    const currentYear = this.currentDate.year();
    new import_obsidian2.Setting(nav).setHeading().setName(`\u041A\u0432\u0430\u0440\u0442\u0430\u043B\u044B ${currentYear}`).settingEl.addClass("heatmap-year-title");
    nav.createEl("button", { text: "\u25C0 \u041F\u0440\u0435\u0434. \u0433\u043E\u0434", cls: "mode-btn" }).onclick = () => {
      this.currentDate.subtract(1, "year");
      this.render();
    };
    nav.createEl("button", { text: "\u0421\u043B\u0435\u0434. \u0433\u043E\u0434 \u25B6", cls: "mode-btn" }).onclick = () => {
      this.currentDate.add(1, "year");
      this.render();
    };
    const quartersGrid = wrapper.createEl("div", { cls: "quarters-grid" });
    for (let q = 1; q <= 4; q++) {
      const quarterStart = (0, import_obsidian2.moment)().year(currentYear).quarter(q).startOf("quarter");
      const quarterFile = this.dailyNotes.find((file) => {
        const data = this.getFileData(file);
        return data && data.type === "quarter" && data.date.year() === currentYear && data.date.quarter() === q;
      });
      const quarterCard = quartersGrid.createEl("div", {
        cls: `quarter-card ${quarterFile ? "quarter-with-note" : ""}`
      });
      const monthsInQuarter = [];
      for (let m = 0; m < 3; m++) {
        const mDate = quarterStart.clone().add(m, "months");
        monthsInQuarter.push(getMonthName(mDate).slice(0, 3));
      }
      quarterCard.createEl("div", { cls: "quarter-title", text: `Q${q}` });
      quarterCard.createEl("div", { cls: "quarter-months", text: monthsInQuarter.join(" \u2022 ") });
      if (quarterFile) {
        quarterCard.createEl("div", { cls: "quarter-badge", text: "\u2705 \u0415\u0441\u0442\u044C \u0437\u0430\u043C\u0435\u0442\u043A\u0430" });
        quarterCard.onmouseenter = () => {
          (async () => {
            try {
              const content = await this.plugin.app.vault.read(quarterFile);
              const preview = content.slice(0, 150).replace(/[#*`]/g, "");
              quarterCard.setAttribute("data-preview", preview + (content.length > 150 ? "..." : ""));
            } catch (error) {
              console.error("Error reading file:", error);
            }
          })().catch(() => {
          });
        };
        quarterCard.onclick = () => this.plugin.app.workspace.openLinkText(quarterFile.path, "", true);
      } else {
        quarterCard.createEl("div", { cls: "quarter-badge quarter-empty", text: "\u274C \u041D\u0435\u0442 \u0437\u0430\u043C\u0435\u0442\u043A\u0438" });
        quarterCard.onclick = () => {
          const folders = this.plugin.settings.watchedFolders.split("\n");
          const path = `${folders[0].trim()}/${currentYear}-Q${q}.md`;
          this.createNoteIfNotExists(path);
        };
      }
    }
  }
  // === МЕСЯЦЫ (отдельный вид) ===
  renderPeriodicMonths(container) {
    const wrapper = container.createEl("div", { cls: "periodic-container" });
    const nav = wrapper.createEl("div", { cls: "panorama-nav" });
    const currentYear = this.currentDate.year();
    new import_obsidian2.Setting(nav).setHeading().setName(`\u041C\u0435\u0441\u044F\u0446\u044B ${currentYear}`).settingEl.addClass("heatmap-year-title");
    nav.createEl("button", { text: "\u25C0 \u041F\u0440\u0435\u0434. \u0433\u043E\u0434", cls: "mode-btn" }).onclick = () => {
      this.currentDate.subtract(1, "year");
      this.render();
    };
    nav.createEl("button", { text: "\u0421\u043B\u0435\u0434. \u0433\u043E\u0434 \u25B6", cls: "mode-btn" }).onclick = () => {
      this.currentDate.add(1, "year");
      this.render();
    };
    const monthsGrid = wrapper.createEl("div", { cls: "periodic-months-grid" });
    for (let m = 0; m < 12; m++) {
      const monthDate = (0, import_obsidian2.moment)().year(currentYear).month(m);
      const monthFile = this.dailyNotes.find((file) => {
        const data = this.getFileData(file);
        return data && data.type === "month" && data.date.year() === currentYear && data.date.month() === m;
      });
      const monthCard = monthsGrid.createEl("div", {
        cls: `periodic-month-card ${monthFile ? "periodic-month-with-note" : ""}`
      });
      monthCard.createEl("div", { cls: "periodic-month-name", text: getMonthName(monthDate).slice(0, 3) });
      if (monthFile) {
        monthCard.addClass("periodic-month-has-note");
        monthCard.onmouseenter = () => {
          (async () => {
            try {
              const content = await this.plugin.app.vault.read(monthFile);
              const preview = content.slice(0, 150).replace(/[#*`]/g, "");
              monthCard.setAttribute("data-preview", preview + (content.length > 150 ? "..." : ""));
            } catch (error) {
              console.error("Error reading file:", error);
            }
          })().catch(() => {
          });
        };
        monthCard.onclick = () => this.plugin.app.workspace.openLinkText(monthFile.path, "", true);
      } else {
        monthCard.onclick = () => {
          const folders = this.plugin.settings.watchedFolders.split("\n");
          const path = `${folders[0].trim()}/${monthDate.format("YYYY-MM")}.md`;
          this.createNoteIfNotExists(path);
        };
      }
    }
  }
  // === НЕДЕЛИ (отдельный вид) ===
  renderPeriodicWeeks(container) {
    const wrapper = container.createEl("div", { cls: "periodic-container" });
    const nav = wrapper.createEl("div", { cls: "panorama-nav" });
    const currentYear = this.currentDate.year();
    new import_obsidian2.Setting(nav).setHeading().setName(`\u041D\u0435\u0434\u0435\u043B\u0438 ${currentYear}`).settingEl.addClass("heatmap-year-title");
    nav.createEl("button", { text: "\u25C0 \u041F\u0440\u0435\u0434. \u0433\u043E\u0434", cls: "mode-btn" }).onclick = () => {
      this.currentDate.subtract(1, "year");
      this.render();
    };
    nav.createEl("button", { text: "\u0421\u043B\u0435\u0434. \u0433\u043E\u0434 \u25B6", cls: "mode-btn" }).onclick = () => {
      this.currentDate.add(1, "year");
      this.render();
    };
    const weeksByMonth = wrapper.createEl("div", { cls: "weeks-by-month" });
    for (let m = 0; m < 12; m++) {
      const monthDate = (0, import_obsidian2.moment)().year(currentYear).month(m);
      const monthStart = monthDate.clone().startOf("month");
      const monthEnd = monthDate.clone().endOf("month");
      const weeksInMonth = [];
      let currentWeek = monthStart.clone().startOf("isoWeek");
      while (currentWeek.isBefore(monthEnd) || currentWeek.isSame(monthEnd, "day")) {
        const weekFile = this.dailyNotes.find((file) => {
          const data = this.getFileData(file);
          return data && data.type === "week" && data.date.year() === currentYear && data.date.isoWeek() === currentWeek.isoWeek();
        });
        weeksInMonth.push({
          weekNum: currentWeek.isoWeek(),
          hasNote: !!weekFile,
          file: weekFile
        });
        currentWeek.add(1, "week");
      }
      const monthBlock = weeksByMonth.createEl("div", { cls: "month-weeks-block" });
      monthBlock.createEl("div", { cls: "month-weeks-title", text: getMonthName(monthDate).slice(0, 3) });
      const weeksContainer = monthBlock.createEl("div", { cls: "weeks-container" });
      weeksInMonth.forEach(({ weekNum, hasNote, file }) => {
        const weekBadge = weeksContainer.createEl("div", {
          cls: `week-badge ${hasNote ? "week-with-note" : "week-empty"}`
        });
        weekBadge.textContent = `W${weekNum.toString().padStart(2, "0")}`;
        if (hasNote && file) {
          weekBadge.onmouseenter = () => {
            (async () => {
              try {
                const content = await this.plugin.app.vault.read(file);
                const preview = content.slice(0, 100).replace(/[#*`]/g, "");
                weekBadge.setAttribute("data-preview", preview + (content.length > 100 ? "..." : ""));
              } catch (error) {
                console.error("Error reading file:", error);
              }
            })().catch(() => {
            });
          };
          weekBadge.onclick = () => this.plugin.app.workspace.openLinkText(file.path, "", true);
        }
      });
    }
  }
  // === ГОДЫ (отдельный вид) ===
  renderPeriodicYears(container) {
    const wrapper = container.createEl("div", { cls: "periodic-container" });
    const nav = wrapper.createEl("div", { cls: "panorama-nav" });
    const currentYear = this.currentDate.year();
    new import_obsidian2.Setting(nav).setHeading().setName("\u0413\u043E\u0434\u044B").settingEl.addClass("heatmap-year-title");
    nav.createEl("button", { text: "\u25C0 \u041D\u0430 5 \u043B\u0435\u0442 \u043D\u0430\u0437\u0430\u0434", cls: "mode-btn" }).onclick = () => {
      this.currentDate.subtract(5, "year");
      this.render();
    };
    nav.createEl("button", { text: "\u041D\u0430 5 \u043B\u0435\u0442 \u0432\u043F\u0435\u0440\u0451\u0434 \u25B6", cls: "mode-btn" }).onclick = () => {
      this.currentDate.add(5, "year");
      this.render();
    };
    const yearsGrid = wrapper.createEl("div", { cls: "years-grid" });
    for (let y = currentYear - 7; y <= currentYear + 7; y++) {
      const yearFile = this.dailyNotes.find((file) => {
        const data = this.getFileData(file);
        return data && data.type === "year" && data.date.year() === y;
      });
      const yearCard = yearsGrid.createEl("div", {
        cls: `year-card ${yearFile ? "year-with-note" : ""} ${y === currentYear ? "current-year" : ""}`
      });
      yearCard.createEl("div", { cls: "year-title", text: y.toString() });
      if (yearFile) {
        yearCard.createEl("div", { cls: "year-badge", text: "\u2705 \u0415\u0441\u0442\u044C" });
        yearCard.onmouseenter = () => {
          (async () => {
            try {
              const content = await this.plugin.app.vault.read(yearFile);
              const preview = content.slice(0, 150).replace(/[#*`]/g, "");
              yearCard.setAttribute("data-preview", preview + (content.length > 150 ? "..." : ""));
            } catch (error) {
              console.error("Error reading file:", error);
            }
          })().catch(() => {
          });
        };
        yearCard.onclick = () => this.plugin.app.workspace.openLinkText(yearFile.path, "", true);
      } else {
        yearCard.createEl("div", { cls: "year-badge year-empty", text: "\u274C \u041D\u0435\u0442" });
        yearCard.onclick = () => {
          const folders = this.plugin.settings.watchedFolders.split("\n");
          const path = `${folders[0].trim()}/${y}.md`;
          this.createNoteIfNotExists(path);
        };
      }
    }
  }
  // === ОБЗОР ВСЕХ ТИПОВ ЗАМЕТОК ===
  renderMonthsOverview(container) {
    const wrapper = container.createEl("div", { cls: "overview-compact-container" });
    const nav = wrapper.createEl("div", { cls: "panorama-nav" });
    new import_obsidian2.Setting(nav).setHeading().setName(`\u041E\u0431\u0437\u043E\u0440 ${this.currentDate.year().toString()}`).settingEl.addClass("heatmap-year-title");
    nav.createEl("button", { text: "\u25C0 \u041F\u0440\u0435\u0434. \u0433\u043E\u0434", cls: "mode-btn" }).onclick = () => {
      this.currentDate.subtract(1, "year");
      this.render();
    };
    nav.createEl("button", { text: "\u0421\u043B\u0435\u0434. \u0433\u043E\u0434 \u25B6", cls: "mode-btn" }).onclick = () => {
      this.currentDate.add(1, "year");
      this.render();
    };
    const currentYear = this.currentDate.year();
    const table = wrapper.createEl("div", { cls: "overview-table" });
    const yearFile = this.dailyNotes.find((file) => {
      const data = this.getFileData(file);
      return data && data.type === "year" && data.date.year() === currentYear;
    });
    const yearRow = table.createEl("div", { cls: "overview-year-row" });
    const yearCell = yearRow.createEl("div", { cls: `overview-cell overview-year ${yearFile ? "has-note" : ""}` });
    yearCell.createEl("strong", { text: String(currentYear) });
    if (yearFile) {
      yearCell.createEl("span", { cls: "note-mark", text: "\u{1F4CB}" });
      yearCell.onclick = () => this.plugin.app.workspace.openLinkText(yearFile.path, "", true);
    } else {
      yearCell.createEl("span", { cls: "note-mark-empty", text: "+" });
      yearCell.onclick = () => {
        const folders = this.plugin.settings.watchedFolders.split("\n");
        this.createNoteIfNotExists(`${folders[0].trim()}/${currentYear}.md`);
      };
    }
    const quartersRow = yearRow.createEl("div", { cls: "overview-quarters-row" });
    for (let q = 1; q <= 4; q++) {
      const quarterFile = this.dailyNotes.find((file) => {
        const data = this.getFileData(file);
        return data && data.type === "quarter" && data.date.year() === currentYear && data.date.quarter() === q;
      });
      const qCell = quartersRow.createEl("div", { cls: `overview-quarter ${quarterFile ? "has-note" : ""}` });
      qCell.textContent = `Q${q}`;
      if (quarterFile) {
        qCell.onclick = () => this.plugin.app.workspace.openLinkText(quarterFile.path, "", true);
      } else {
        qCell.onclick = () => {
          const folders = this.plugin.settings.watchedFolders.split("\n");
          this.createNoteIfNotExists(`${folders[0].trim()}/${currentYear}-Q${q}.md`);
        };
      }
    }
    const monthsGrid = table.createEl("div", { cls: "overview-months-grid" });
    for (let m = 0; m < 12; m++) {
      const monthFile = this.dailyNotes.find((file) => {
        const data = this.getFileData(file);
        return data && data.type === "month" && data.date.year() === currentYear && data.date.month() === m;
      });
      let dayCount = 0;
      this.dailyNotes.forEach((file) => {
        const data = this.getFileData(file);
        if (data && data.type === "day" && data.date.year() === currentYear && data.date.month() === m) {
          dayCount++;
        }
      });
      const monthCell = monthsGrid.createEl("div", { cls: `overview-month ${monthFile ? "has-note" : ""}` });
      const monthName = getMonthName((0, import_obsidian2.moment)().year(currentYear).month(m)).slice(0, 3);
      monthCell.createEl("span", { cls: "month-name", text: monthName });
      if (dayCount > 0) {
        monthCell.createEl("span", { cls: "day-count", text: `${dayCount}\u0434` });
      }
      if (monthFile) {
        monthCell.classList.add("month-with-monthly-note");
        monthCell.onclick = () => this.plugin.app.workspace.openLinkText(monthFile.path, "", true);
      } else {
        monthCell.onclick = () => {
          const folders = this.plugin.settings.watchedFolders.split("\n");
          this.createNoteIfNotExists(`${folders[0].trim()}/${(0, import_obsidian2.moment)().year(currentYear).month(m).format("YYYY-MM")}.md`);
        };
      }
    }
    const statsSection = wrapper.createEl("div", { cls: "overview-stats-section" });
    const typeCounts = { day: 0, week: 0, month: 0, quarter: 0, year: 0 };
    this.dailyNotes.forEach((file) => {
      const result = this.getFileData(file);
      if (result && result.date.year() === currentYear) {
        if (typeCounts[result.type] !== void 0) {
          typeCounts[result.type]++;
        }
      }
    });
    new import_obsidian2.Setting(statsSection).setHeading().setName(`\u{1F4CA} \u0417\u0430\u043C\u0435\u0442\u043A\u0438 \u0437\u0430 ${currentYear} \u0433\u043E\u0434`).settingEl.addClass("overview-stats-title");
    const statsBadges = statsSection.createEl("div", { cls: "overview-stats-badges" });
    statsBadges.createEl("span", { cls: "overview-stat-badge stat-day", text: `\u{1F4C5} \u0414\u043D\u0438: ${typeCounts.day}` });
    statsBadges.createEl("span", { cls: "overview-stat-badge stat-week", text: `\u{1F4C6} \u041D\u0435\u0434\u0435\u043B\u0438: ${typeCounts.week}` });
    statsBadges.createEl("span", { cls: "overview-stat-badge stat-month", text: `\u{1F5D3}\uFE0F \u041C\u0435\u0441\u044F\u0446\u044B: ${typeCounts.month}` });
    statsBadges.createEl("span", { cls: "overview-stat-badge stat-quarter", text: `\u{1F4CA} \u041A\u0432\u0430\u0440\u0442\u0430\u043B\u044B: ${typeCounts.quarter}` });
    statsBadges.createEl("span", { cls: "overview-stat-badge stat-year", text: `\u{1F3AF} \u0413\u043E\u0434\u044B: ${typeCounts.year}` });
  }
  async createNoteIfNotExists(path) {
    if (!this.plugin.app.vault.getAbstractFileByPath(path)) {
      const folder = path.split("/").slice(0, -1).join("/");
      if (!this.plugin.app.vault.getAbstractFileByPath(folder)) {
        await this.plugin.app.vault.createFolder(folder);
      }
      await this.plugin.app.vault.create(path, "");
      if (this.plugin.settings.useTemplater && this.plugin.templater) {
        await this.applyTemplaterTemplate(path);
      }
      this.updateData();
    }
    await this.plugin.app.workspace.openLinkText(path, "", true);
  }
  async applyTemplaterTemplate(path) {
    var _a;
    const fileName = ((_a = path.split("/").pop()) == null ? void 0 : _a.replace(".md", "")) || "";
    let templateName = "";
    if (fileName.match(/^\d{2}\.\d{2}\.\d{2}$/) || fileName.match(/^\d{4}-\d{2}-\d{2}$/)) {
      templateName = this.plugin.settings.dailyTemplate;
    } else if (fileName.match(/\d{4}-W\d{2}/)) {
      templateName = this.plugin.settings.weeklyTemplate;
    } else if (fileName.match(/^\d{4}-\d{2}$/)) {
      templateName = this.plugin.settings.monthlyTemplate;
    }
    if (!templateName)
      return;
    if (!this.plugin.settings.templatesFolder)
      return;
    try {
      const templatePath = `${this.plugin.settings.templatesFolder}/${templateName}.md`;
      const templateFile = this.plugin.app.vault.getAbstractFileByPath(templatePath);
      if (!templateFile)
        return;
      const targetFile = this.plugin.app.vault.getAbstractFileByPath(path);
      if (!targetFile)
        return;
      await this.plugin.templater.templater.write_template_to_file(templateFile, targetFile);
    } catch (error) {
      console.error("Templater error:", error);
    }
  }
  renderStatistics(container) {
    const box = container.createEl("div", { cls: "stats-container" });
    new import_obsidian2.Setting(box).setHeading().setName("\u{1F4C8} \u041F\u0440\u043E\u0433\u0440\u0435\u0441\u0441");
    box.createEl("p", { cls: "stat-item" }).createEl("strong", { text: `\u{1F525} \u0422\u0435\u043A\u0443\u0449\u0430\u044F \u0441\u0435\u0440\u0438\u044F: ${this.stats.currentStreak} \u0434\u043D.` });
    box.createEl("p", { cls: "stat-item" }).createEl("strong", { text: `\u{1F4C5} \u041F\u043E\u0441\u043B\u0435\u0434\u043D\u044F\u044F \u0437\u0430\u043F\u0438\u0441\u044C: ${this.stats.lastNoteDate}` });
    box.createEl("p", { cls: "stat-item" }).createEl("strong", { text: `\u23F0 \u041F\u0440\u043E\u0448\u043B\u043E \u0432\u0440\u0435\u043C\u0435\u043D\u0438: ${this.stats.timeSinceLastNote}` });
    box.createEl("hr", { cls: "stat-divider" });
    const yearTypeCounts = /* @__PURE__ */ new Map();
    this.dailyNotes.forEach((file) => {
      const result = this.getFileData(file);
      if (result) {
        const noteYear = result.date.year();
        if (!yearTypeCounts.has(noteYear)) {
          yearTypeCounts.set(noteYear, { day: 0, week: 0, month: 0, quarter: 0, year: 0 });
        }
        const counts = yearTypeCounts.get(noteYear);
        if (counts[result.type] !== void 0) {
          counts[result.type]++;
        }
      }
    });
    const sortedYears = Array.from(yearTypeCounts.keys()).sort((a, b) => b - a);
    const latestYear = sortedYears.length > 0 ? sortedYears[0] : (0, import_obsidian2.moment)().year();
    if (yearTypeCounts.has(latestYear)) {
      const counts = yearTypeCounts.get(latestYear);
      const yearRow = box.createEl("div", { cls: "stat-year-compact" });
      yearRow.createEl("span", { cls: "stat-year-label", text: `${latestYear}:` });
      if (counts.day > 0)
        yearRow.createEl("span", { cls: "stat-badge stat-type-day", text: `\u{1F4C5} ${counts.day}` });
      if (counts.week > 0)
        yearRow.createEl("span", { cls: "stat-badge stat-type-week", text: `\u{1F4C6} ${counts.week}` });
      if (counts.month > 0)
        yearRow.createEl("span", { cls: "stat-badge stat-type-month", text: `\u{1F5D3}\uFE0F ${counts.month}` });
      if (counts.quarter > 0)
        yearRow.createEl("span", { cls: "stat-badge stat-type-quarter", text: `\u{1F4CA} ${counts.quarter}` });
      if (counts.year > 0)
        yearRow.createEl("span", { cls: "stat-badge stat-type-year", text: `\u{1F3AF} ${counts.year}` });
    }
    box.createEl("hr", { cls: "stat-divider" });
    box.createEl("p", { cls: "stat-item" }).createEl("strong", { text: `\u{1F4DD} \u0412\u0441\u0435\u0433\u043E \u0437\u0430\u043C\u0435\u0442\u043E\u043A: ${this.dailyNotes.length}` });
    const currentYear = (0, import_obsidian2.moment)().year();
    const lastYear = currentYear - 1;
    const lastYearStart = (0, import_obsidian2.moment)().year(lastYear).startOf("year");
    const lastYearEnd = (0, import_obsidian2.moment)().year(lastYear).endOf("year");
    const daysInLastYear = lastYearEnd.diff(lastYearStart, "days") + 1;
    let lastYearDayNotes = 0;
    this.dailyNotes.forEach((file) => {
      const result = this.getFileData(file);
      if (result && result.type === "day" && result.date.year() === lastYear) {
        lastYearDayNotes++;
      }
    });
    const lastYearFillPercentage = daysInLastYear > 0 ? Math.round(lastYearDayNotes / daysInLastYear * 100) : 0;
    const currentYearStart = (0, import_obsidian2.moment)().year(currentYear).startOf("year");
    const daysPassed = (0, import_obsidian2.moment)().diff(currentYearStart, "days") + 1;
    let currentYearDayNotes = 0;
    this.dailyNotes.forEach((file) => {
      const result = this.getFileData(file);
      if (result && result.type === "day" && result.date.year() === currentYear) {
        currentYearDayNotes++;
      }
    });
    const currentYearFillPercentage = daysPassed > 0 ? Math.round(currentYearDayNotes / daysPassed * 100) : 0;
    const compareRow = box.createEl("div", { cls: "stat-year-compare" });
    compareRow.createEl("strong", { text: "\u{1F4C8} \u0417\u0430\u043F\u043E\u043B\u043D\u0435\u043D\u0438\u0435:" });
    compareRow.createEl("br");
    const span1 = compareRow.createEl("span", { cls: "stat-compare-item" });
    span1.createEl("strong", { text: `${lastYear}: ` });
    span1.appendText(`${lastYearFillPercentage}% (${lastYearDayNotes}/${daysInLastYear})`);
    const span2 = compareRow.createEl("span", { cls: "stat-compare-item" });
    span2.createEl("strong", { text: `${currentYear}: ` });
    span2.appendText(`${currentYearFillPercentage}% (${currentYearDayNotes}/${daysPassed})`);
  }
  renderRetroModule(container) {
    const box = container.createEl("div", { cls: "memory-box" });
    const head = box.createEl("div", { cls: "retro-header" });
    new import_obsidian2.Setting(head).setHeading().setName("\u{1F570} \u0420\u0435\u0442\u0440\u043E");
    const ctrls = box.createEl("div", { cls: "retro-controls" });
    const btnDay = ctrls.createEl("button", { cls: "retro-btn", text: "\u{1F4C5} \u042D\u0442\u043E\u0442 \u0434\u0435\u043D\u044C" });
    const btnRnd = ctrls.createEl("button", { cls: "retro-btn", text: "\u{1F3B2} \u0420\u0430\u043D\u0434\u043E\u043C" });
    const preview = box.createEl("div", { cls: "memory-preview" });
    btnDay.onclick = () => {
      (() => {
        const notes = getNotesOnThisDay(this.dailyNotes);
        if (notes.length)
          this.showPreview(notes[0], preview);
        else {
          preview.empty();
          preview.createEl("span", { text: "\u041F\u0443\u0441\u0442\u043E..." });
        }
      })();
    };
    btnRnd.onclick = () => {
      (async () => {
        const note = await getRandomQualityNote(this.plugin.app, this.dailyNotes);
        if (note)
          this.showPreview(note, preview);
      })().catch(() => {
      });
    };
    btnDay.click();
  }
  async showPreview(file, container) {
    try {
      const content = await this.plugin.app.vault.read(file);
      container.empty();
      new import_obsidian2.Setting(container).setHeading().setName(file.name.replace(".md", "")).settingEl.addClass("preview-date");
      const contentEl = container.createEl("div", { cls: "preview-content" });
      contentEl.textContent = content;
      container.createEl("button", { cls: "preview-open-button", text: "\u{1F4C2} \u041E\u0442\u043A\u0440\u044B\u0442\u044C \u0432 Obsidian" }).onclick = () => this.plugin.app.workspace.openLinkText(file.path, "", true);
    } catch (error) {
      console.error("Error reading file:", error);
    }
  }
  async createNote(dateStr) {
    const folders = this.plugin.settings.watchedFolders.split("\n");
    const formats = this.plugin.settings.dateFormats.split("\n");
    const path = `${folders[0].trim()}/${(0, import_obsidian2.moment)(dateStr).format(formats[0].trim())}.md`;
    if (!this.plugin.app.vault.getAbstractFileByPath(path)) {
      const folder = folders[0].trim();
      if (!this.plugin.app.vault.getAbstractFileByPath(folder))
        await this.plugin.app.vault.createFolder(folder);
      await this.plugin.app.vault.create(path, "");
      if (this.plugin.settings.useTemplater && this.plugin.templater) {
        await this.applyTemplaterTemplate(path);
      }
      this.updateData();
    }
    await this.plugin.app.workspace.openLinkText(path, "", true);
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  // Ваши папки по умолчанию
  watchedFolders: "Daily Notes\n2. Areas/diary",
  // Форматы:
  // 1. DD.MM.YY (Ваш основной: 30.12.24)
  // 2. Стандартные (YYYY-MM-DD, DD.MM.YYYY)
  // 3. Периодические заметки (Недели, Месяцы, Кварталы, Годы)
  dateFormats: "DD.MM.YY\nDD.MM.YYYY\nYYYY-MM-DD\ngggg-[W]ww\nYYYY-MM\nYYYY-[Q]Q\nYYYY",
  // Templater
  useTemplater: false,
  templatesFolder: "5. Utils/Templates",
  dailyTemplate: "",
  weeklyTemplate: "",
  monthlyTemplate: ""
};
var HabitTrackerPlugin = class extends import_obsidian3.Plugin {
  // Templater API
  async onload() {
    console.debug("\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430 \u043F\u043B\u0430\u0433\u0438\u043D\u0430 Life Calendar");
    await this.loadSettings();
    this.templater = this.app.plugins.plugins["templater-obsidian"];
    this.registerView(
      VIEW_TYPE_HABIT_TRACKER,
      (leaf) => new HabitTrackerView(leaf, this)
    );
    this.addCommand({
      id: "open-habit-tracker",
      name: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u0442\u0440\u0435\u043A\u0435\u0440 \u043F\u0440\u0438\u0432\u044B\u0447\u0435\u043A",
      callback: () => {
        this.activateView();
      }
    });
    this.addRibbonIcon("calendar-days", "\u0422\u0440\u0435\u043A\u0435\u0440 \u043F\u0440\u0438\u0432\u044B\u0447\u0435\u043A", () => {
      this.activateView();
    });
    this.addSettingTab(new HabitTrackerSettingTab(this.app, this));
  }
  onunload() {
    console.debug("\u0412\u044B\u0433\u0440\u0443\u0437\u043A\u0430 \u043F\u043B\u0430\u0433\u0438\u043D\u0430 Life Calendar");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_HABIT_TRACKER)[0];
    if (!leaf) {
      leaf = workspace.getLeaf(true);
    }
    await leaf.setViewState({
      type: VIEW_TYPE_HABIT_TRACKER,
      active: true
    });
    workspace.revealLeaf(leaf);
  }
  /**
   * Получить все заметки, соответствующие настроенным папкам и форматам
   */
  getDailyNotes() {
    const folders = this.settings.watchedFolders.split("\n").map((f) => f.trim()).filter((f) => f.length > 0);
    const formats = this.settings.dateFormats.split("\n").map((f) => f.trim()).filter((f) => f.length > 0);
    const allFiles = this.app.vault.getMarkdownFiles();
    return allFiles.filter((file) => {
      const isInWatchedFolder = folders.some((folder) => file.path.startsWith(folder));
      if (!isInWatchedFolder)
        return false;
      const nameWithoutExt = file.name.replace(/\.md$/, "");
      const isValidDate = formats.some(
        (format) => (0, import_obsidian3.moment)(nameWithoutExt, format, true).isValid()
      );
      return isValidDate;
    });
  }
};
var HabitTrackerSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.focusHandler = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const oldDatalist = document.getElementById("folder-suggestions");
    if (oldDatalist)
      oldDatalist.remove();
    new import_obsidian3.Setting(containerEl).setHeading().setName("\u0418\u0441\u0442\u043E\u0447\u043D\u0438\u043A\u0438 \u0434\u0430\u043D\u043D\u044B\u0445");
    const hasTemplater = this.plugin.templater !== void 0;
    new import_obsidian3.Setting(containerEl).setHeading().setName("\u{1F3A8} Templater \u0418\u043D\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044F");
    new import_obsidian3.Setting(containerEl).setName("\u0418\u0441\u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u044C Templater").setDesc(hasTemplater ? "\u041F\u0440\u0438\u043C\u0435\u043D\u044F\u0442\u044C \u0448\u0430\u0431\u043B\u043E\u043D\u044B Templater \u043F\u0440\u0438 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u0438 \u043D\u043E\u0432\u044B\u0445 \u0437\u0430\u043C\u0435\u0442\u043E\u043A" : "\u26A0\uFE0F Templater \u043D\u0435 \u0443\u0441\u0442\u0430\u043D\u043E\u0432\u043B\u0435\u043D! \u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u0435 \u0435\u0433\u043E \u0434\u043B\u044F \u0438\u0441\u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u043D\u0438\u044F \u044D\u0442\u043E\u0439 \u0444\u0443\u043D\u043A\u0446\u0438\u0438.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.useTemplater).setDisabled(!hasTemplater).onChange(async (value) => {
        this.plugin.settings.useTemplater = value;
        await this.plugin.saveSettings();
      });
    });
    if (hasTemplater) {
      new import_obsidian3.Setting(containerEl).setName("\u041F\u0430\u043F\u043A\u0430 \u0441 \u0448\u0430\u0431\u043B\u043E\u043D\u0430\u043C\u0438 Templater").setDesc("\u0423\u043A\u0430\u0436\u0438 \u043F\u0443\u0442\u044C \u043A \u043F\u0430\u043F\u043A\u0435, \u0433\u0434\u0435 \u0445\u0440\u0430\u043D\u044F\u0442\u0441\u044F \u0448\u0430\u0431\u043B\u043E\u043D\u044B").addText((text) => {
        text.setPlaceholder("5. Utils/Templates").setValue(this.plugin.settings.templatesFolder).onChange(async (value) => {
          this.plugin.settings.templatesFolder = value;
          await this.plugin.saveSettings();
        });
        if (this.focusHandler) {
          text.inputEl.removeEventListener("focus", this.focusHandler);
        }
        this.focusHandler = () => {
          const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian3.TFolder).map((f) => f.path).sort();
          const oldDatalist2 = document.getElementById("folder-suggestions");
          if (oldDatalist2)
            oldDatalist2.remove();
          const dataList = document.createElement("datalist");
          dataList.id = "folder-suggestions";
          folders.forEach((folder) => {
            const option = document.createElement("option");
            option.value = folder;
            dataList.appendChild(option);
          });
          text.inputEl.setAttribute("list", "folder-suggestions");
          document.body.appendChild(dataList);
        };
        text.inputEl.addEventListener("focus", this.focusHandler);
      });
      new import_obsidian3.Setting(containerEl).setName("\u0428\u0430\u0431\u043B\u043E\u043D \u0434\u043B\u044F \u0434\u043D\u0435\u0432\u043D\u044B\u0445 \u0437\u0430\u043C\u0435\u0442\u043E\u043A").setDesc("\u0418\u043C\u044F \u0444\u0430\u0439\u043B\u0430 \u0448\u0430\u0431\u043B\u043E\u043D\u0430 (\u0431\u0435\u0437 \u0440\u0430\u0441\u0448\u0438\u0440\u0435\u043D\u0438\u044F)").addText((text) => {
        text.setPlaceholder("FOR Dayly Notes planing").setValue(this.plugin.settings.dailyTemplate).onChange(async (value) => {
          this.plugin.settings.dailyTemplate = value;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian3.Setting(containerEl).setName("\u0428\u0430\u0431\u043B\u043E\u043D \u0434\u043B\u044F \u043D\u0435\u0434\u0435\u043B\u044C\u043D\u044B\u0445 \u0437\u0430\u043C\u0435\u0442\u043E\u043A").setDesc("\u0418\u043C\u044F \u0444\u0430\u0439\u043B\u0430 \u0448\u0430\u0431\u043B\u043E\u043D\u0430 (\u0431\u0435\u0437 \u0440\u0430\u0441\u0448\u0438\u0440\u0435\u043D\u0438\u044F)").addText((text) => {
        text.setPlaceholder("Weekly template").setValue(this.plugin.settings.weeklyTemplate).onChange(async (value) => {
          this.plugin.settings.weeklyTemplate = value;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian3.Setting(containerEl).setName("\u0428\u0430\u0431\u043B\u043E\u043D \u0434\u043B\u044F \u043C\u0435\u0441\u044F\u0447\u043D\u044B\u0445 \u0437\u0430\u043C\u0435\u0442\u043E\u043A").setDesc("\u0418\u043C\u044F \u0444\u0430\u0439\u043B\u0430 \u0448\u0430\u0431\u043B\u043E\u043D\u0430 (\u0431\u0435\u0437 \u0440\u0430\u0441\u0448\u0438\u0440\u0435\u043D\u0438\u044F)").addText((text) => {
        text.setPlaceholder("Monthly template").setValue(this.plugin.settings.monthlyTemplate).onChange(async (value) => {
          this.plugin.settings.monthlyTemplate = value;
          await this.plugin.saveSettings();
        });
      });
    }
    containerEl.createEl("hr", { cls: "habit-tracker-divider" });
    new import_obsidian3.Setting(containerEl).setHeading().setName("\u{1F4C2} \u041F\u0430\u043F\u043A\u0438 \u0438 \u0444\u043E\u0440\u043C\u0430\u0442\u044B");
    new import_obsidian3.Setting(containerEl).setName("\u041F\u0430\u043F\u043A\u0438 \u0441 \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u043C\u0438").setDesc("\u0421\u043F\u0438\u0441\u043E\u043A \u043F\u0430\u043F\u043E\u043A \u0434\u043B\u044F \u0441\u043A\u0430\u043D\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F (\u043A\u0430\u0436\u0434\u0430\u044F \u0441 \u043D\u043E\u0432\u043E\u0439 \u0441\u0442\u0440\u043E\u043A\u0438). \u041F\u043B\u0430\u0433\u0438\u043D \u0440\u0435\u043A\u0443\u0440\u0441\u0438\u0432\u043D\u043E \u0441\u043A\u0430\u043D\u0438\u0440\u0443\u0435\u0442 \u044D\u0442\u0438 \u043F\u0430\u043F\u043A\u0438.").addTextArea((text) => {
      text.setPlaceholder("Daily Notes\n2. Areas/diary").setValue(this.plugin.settings.watchedFolders).onChange(async (value) => {
        this.plugin.settings.watchedFolders = value;
        await this.plugin.saveSettings();
        this.refreshView();
      });
      text.inputEl.rows = 4;
    });
    new import_obsidian3.Setting(containerEl).setName("\u0424\u043E\u0440\u043C\u0430\u0442\u044B \u0434\u0430\u0442").setDesc("\u0423\u043A\u0430\u0436\u0438\u0442\u0435 \u0444\u043E\u0440\u043C\u0430\u0442\u044B \u0438\u043C\u0435\u043D \u0444\u0430\u0439\u043B\u043E\u0432 (\u0441\u0438\u043D\u0442\u0430\u043A\u0441\u0438\u0441 Moment.js). \u041F\u043E\u0434\u0434\u0435\u0440\u0436\u0438\u0432\u0430\u044E\u0442\u0441\u044F \u0434\u043D\u0435\u0432\u043D\u044B\u0435, \u043D\u0435\u0434\u0435\u043B\u044C\u043D\u044B\u0435, \u043C\u0435\u0441\u044F\u0447\u043D\u044B\u0435 \u0438 \u0433\u043E\u0434\u043E\u0432\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438.").addTextArea((text) => {
      text.setPlaceholder("DD.MM.YY\nYYYY-MM-DD").setValue(this.plugin.settings.dateFormats).onChange(async (value) => {
        this.plugin.settings.dateFormats = value;
        await this.plugin.saveSettings();
        this.refreshView();
      });
      text.inputEl.rows = 8;
    });
    const helpDiv = containerEl.createEl("div", { cls: "habit-tracker-help" });
    new import_obsidian3.Setting(helpDiv).setHeading().setName("\u{1F4D6} \u041F\u043E\u0434\u0434\u0435\u0440\u0436\u0438\u0432\u0430\u0435\u043C\u044B\u0435 \u0444\u043E\u0440\u043C\u0430\u0442\u044B:");
    helpDiv.createEl("p").createEl("strong", { text: "\u0414\u043D\u0435\u0432\u043D\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438:" });
    helpDiv.createEl("ul", {}, (ul) => {
      ul.createEl("li", { text: "DD.MM.YY \u2014 30.12.24" });
      ul.createEl("li", { text: "DD.MM.YYYY \u2014 30.12.2024" });
      ul.createEl("li", { text: "YYYY-MM-DD \u2014 2024-12-30" });
    });
    helpDiv.createEl("p").createEl("strong", { text: "\u041F\u0435\u0440\u0438\u043E\u0434\u0438\u0447\u0435\u0441\u043A\u0438\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438:" });
    helpDiv.createEl("ul", {}, (ul) => {
      ul.createEl("li", { text: "gggg-[W]ww \u2014 2024-W01 (\u041D\u0435\u0434\u0435\u043B\u044F, \u043E\u0442\u043E\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044F \u0432 \u043F\u043E\u043D\u0435\u0434\u0435\u043B\u044C\u043D\u0438\u043A)" });
      ul.createEl("li", { text: "YYYY-MM \u2014 2024-12 (\u041C\u0435\u0441\u044F\u0446, \u043E\u0442\u043E\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044F 1-\u0433\u043E \u0447\u0438\u0441\u043B\u0430)" });
      ul.createEl("li", { text: "YYYY-[Q]Q \u2014 2024-Q1 (\u041A\u0432\u0430\u0440\u0442\u0430\u043B, \u043E\u0442\u043E\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044F 1-\u0433\u043E \u0447\u0438\u0441\u043B\u0430)" });
      ul.createEl("li", { text: "YYYY \u2014 2024 (\u0413\u043E\u0434, \u043E\u0442\u043E\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044F 1 \u044F\u043D\u0432\u0430\u0440\u044F)" });
    });
  }
  refreshView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_HABIT_TRACKER);
    leaves.forEach((leaf) => {
      if (leaf.view instanceof HabitTrackerView) {
        leaf.view.updateData();
      }
    });
  }
};
